OBJ =  P95972_Sum_of_Divisors.o 
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
	$(CXX) $(CXXFLAGS)  P95972_Sum_of_Divisors.o -o  P95972_Sum_of_Divisors

clean:
	rm -rf *.o *.txt 
	rm  P95972_Sum_of_Divisors