OBJ = P58459_Valid_Dates.o 
CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wpedantic

programa: $(OBJ)
	$(CXX) $(CXXFLAGS) P58459_Valid_Dates.o -o P58459_Valid_Dates

clean:
	rm -rf *.o *.txt 
	rm P58459_Valid_Dates